la mia pizzeria/Models/Pizza.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace la_mia_pizzeria.Models
{
    public class Pizza
    {
        [Key]
        public int Id { get; set; }

        [Required]       
        public string Nome { get; set; }
        [Required]
        public string Descrizione { get; set; }

        [Required]
        [Range(1,100)]
        public double Prezzo { get; set; }

        [Required]
        public string Immagine { get; set; }

        public Categoria? Categoria { get; set; }

        [ForeignKey("Categoria")]
        public string CategoriaNome { get; set; }

        public List<Ingrediente>? Ingredienti { get; set; }

        public Pizza()
        {

        }

        public Pizza (string nome, string descrizione, double prezzo, string immagine)
        {
            this.Nome = nome;
            this.Descrizione = descrizione;
            this.Prezzo = prezzo;
            this.Immagine = immagine;
        }
    }
}

la mia pizzeria/Controllers/PizzaController.cs
using Azure;
using la_mia_pizzeria.Database;
using la_mia_pizzeria.Models;
using la_mia_pizzeria.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;

namespace la_mia_pizzeria.Controllers
{ 
    public class PizzaController : Controller
    {
        

        public IActionResult Index()
        {
            using (PizzeriaContext db = new PizzeriaContext())
            {
                List<Pizza>? ListaPizze = db.Pizze.Where(p=>p.Categoria.Nome=="Pizze Speciali").ToList<Pizza>();

                return View("Index", ListaPizze);
            }
        }

        [Authorize]
        public IActionResult LeNostrePizzeAdmin()
        {
            using (PizzeriaContext db = new PizzeriaContext())
            {
                List<Pizza> ListaPizze = db.Pizze.ToList<Pizza>();

                return View("LeNostrePizze", ListaPizze);
            }

        }

        public IActionResult IlNostroMenu()
        {
            return View();
        }

        public IActionResult Dettagli(int ID)
        {
            using (PizzeriaContext db = new PizzeriaContext())
            {
                Pizza? pizza = db.Pizze.Where(p=>p.Id==ID).Include(pi=>pi.Categoria).Include(piz=>piz.Ingredienti).FirstOrDefault();
                if (pizza != null)
                {
                    return View(pizza);
                }
                else
                {
                    return NotFound("La pizza ricercata non è presente a listino");
                }

            }
        }

        [HttpGet]
        [Authorize]
        public IActionResult NuovaPizza()
        {
            using PizzeriaContext db = new();
            List<Categoria> Categorie= db.Categorie.ToList();
            List<Ingrediente> Ingredienti = db.Ingredienti.ToList();
            CategoriaPizzaView modelloView = new()
            {
                Pizza = new Pizza(),
                Categorie = Categorie,
                ListaIngredienti = SelectItemManager.ConverterListIngredient()
            };

            return View("NuovaPizza", modelloView);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult NuovaPizza(CategoriaPizzaView formData)
        {
            if (!ModelState.IsValid)
            {
                using PizzeriaContext db = new();
                List<Categoria> categorie = db.Categorie.ToList();
                formData.Categorie = categorie;
                formData.ListaIngredienti = SelectItemManager.ConverterListIngredient();
                return View("NuovaPizza", formData);
            }

            using (PizzeriaContext db = new PizzeriaContext())
            {
                if(formData.ListaIdIngredienti != null)
                {
                    formData.Pizza.Ingredienti = new();
                    foreach(string IdIngrediente in formData.ListaIdIngredienti)
                    {
                        int IDNumero = int.Parse(IdIngrediente);
                        Ingrediente? ingrediente = db.Ingredienti.Where(i=>i.IngredienteId== IDNumero).FirstOrDefault();
                        formData.Pizza.Ingredienti.Add(ingrediente);
                    }
                }
                db.Pizze.Add(formData.Pizza);
                db.SaveChanges();

            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize]
        public IActionResult ModificaPizza(int ID)
        {

            using (PizzeriaContext db = new PizzeriaContext())
            {
                Pizza? pizza = db.Pizze.Where(p=>p.Id==ID).Include(pi=>pi.Ingredienti).FirstOrDefault();
                if (pizza != null)
                {
                    List<Categoria> Categorie = db.Categorie.ToList();
                    CategoriaPizzaView modelloView = new()
                    {
                        Pizza = pizza,
                        Categorie = Categorie
                    };
                    List<Ingrediente> IngredientiDb = db.Ingredienti.ToList();
                    List<SelectListItem> ListItem = new();
                    foreach(Ingrediente ingrediente in IngredientiDb)
                    {
                        bool Selected = pizza.Ingredienti.Any(ing => ing.IngredienteId == ingrediente.IngredienteId);

                        SelectListItem Option = new SelectListItem() { 
                            Text = ingrediente.Condimento,
                            Value = ingrediente.IngredienteId.ToString(),
                            Selected = Selected };
                        ListItem.Add(Option);
                    }
                    modelloView.ListaIngredienti = ListItem;
                    return View("ModificaPizza", modelloView);
                }
                else
                {
                    return NotFound("La pizza ricercata non è presente a listino");
                }

            }
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult ModificaPizza(int ID, CategoriaPizzaView formData)
        {
            if (!ModelState.IsValid)
            {
                using PizzeriaContext db = new();
                List<Categoria> categorie = db.Categorie.ToList();
                formData.Categorie = categorie;
                return View("ModificaPizza", formData);
            }

            using (PizzeriaContext db = new PizzeriaContext())
            {
                Pizza? pizza = db.Pizze.Where(p => p.Id == ID).Include(pi => pi.Ingredienti).FirstOrDefault();
                if (pizza != null)
                {
                    pizza.Nome = formData.Pizza.Nome;
                    pizza.Descrizione = formData.Pizza.Descrizione;
                    pizza.Immagine = formData.Pizza.Immagine;
                    pizza.Prezzo = formData.Pizza.Prezzo;
                    pizza.CategoriaNome = formData.Pizza.CategoriaNome;

                    pizza.Ingredienti.Clear();
                    if (formData.ListaIdIngredienti != null)
                    {
                        foreach (string IdIngrediente in formData.ListaIdIngredienti)
                        {
                            int IDNumero = int.Parse(IdIngrediente);
                            Ingrediente? ingrediente = db.Ingredienti.Where(i => i.IngredienteId == IDNumero).FirstOrDefault();
                            pizza.Ingredienti.Add(ingrediente);
                        }
                    }

                    db.SaveChanges();
                }

            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult EliminaPizza(int ID)
        {

            using (PizzeriaContext db = new PizzeriaContext())
            {
                Pizza? pizzadaEliminare = (from pi in db.Pizze
                                           where pi.Id == ID
                                           select pi).FirstOrDefault();
                if (pizzadaEliminare != null)
                {
                    db.Remove(pizzadaEliminare);

                    db.SaveChanges();
                }

            }
            return RedirectToAction("Index");
        }
    }
}

la mia pizzeria/Views/Pizza/Dettagli.cshtml
@model Pizza

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="d-flex align-items-center">
                <h1 class="mt-3 mb-3">Dettagli Pizze</h1>
            </div>
            <div id="pizza_container">
                
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script type="text/javascript">
        const id = window.location.href.substring(window.location.href.lastIndexOf('/') + 1)
        axios.get(`https://localhost:7237/api/pizze/${id}`).then((res) => {
            let pizza = res.data;
            console.log('pizza ricevuta', pizza);


            document.getElementById('pizza_container').innerHTML +=
                `
                                            <div class="post-single-image-container">
                            <img src="${pizza.immagine}" width=100%>
                        </div>
                        <p>
                            <strong>Nome:</strong>
        ${pizza.nome}
                        </p>
                        <p>
                            <strong>Ingredienti:</strong>
        ${pizza.descrizione}
                        </p>
                        <p>
                            <strong>Categoria:</strong>
        ${pizza.categoriaNome}
                        </p>
                        <p>                      
                                `;

        });
    </script>
}

la mia pizzeria/Views/Pizza/IlNostroMenu.cshtml
<main>
<h1 class="mt-3 mb-3">La nostra offerta:</h1>
<div>
    <input id="input_search" type="text" class="form-control mb-5" placeholder="Cerca..." />
</div>

<div class="container-flex">

    <div class="justify-content-center mb-3">

        <h3 class="js_no_pizze_menu d-none">Il nostro olimpo è vuoto, ci scusiamo per il disagio</h3>
        <div class="d-none js_pizza_table_menu row">
        </div>
    </div>
</div>
</main>


@section Scripts {
    <script type="text/javascript">

        debugger;
        loadAMenu();
        document.getElementById('input_search').addEventListener('keyup', searchPizzas);

        function searchPizzas() {
            let stringaDiRicerca = document.getElementById('input_search').value;
            loadAMenu(stringaDiRicerca);
        }

    </script>
}

la mia pizzeria/Views/Pizza/Index.cshtml
@model List<Pizza>

@{

}

<main class="container text-center">

    <h1>Chi siamo</h1>

    <img src="/img/scroll.png" width=50% />

    <h1 class="my-3">Il nostro olimpo</h1>
    <p>Qui trovi le nostre pizze migliori, le grandi star del nostro pantheon</p>

    <div class="container-flex">

        <div class="justify-content-center mb-3">

            <h3 class="js_no_pizze d-none">Il nostro olimpo è vuoto, ci scusiamo per il disagio</h3>
            <div class="d-none js_pizza_table row">
            </div>
        </div>
        <div class="my-2"><a asp-controller="Pizza" asp-action="IlNostroMenu" class="text-black"><h2>Scopri le nostre pizze</h2></a></div>
        @if (User.Identity.IsAuthenticated)
        {
            <div class="my-2"><a asp-controller="Pizza" asp-action="LeNostrePizzeAdmin" class="text-black"><h2>Area Admin</h2></a></div>
        }
    </div>

</main>

@section Scripts {
    <script type="text/javascript">

            let search = "speciali";
            loadAPizze(search);
</script>
}

la mia pizzeria/Views/Pizza/LeNostrePizze.cshtml
@model List<Pizza>

@if (Model.Count == 0)
{
    <h3>Non sono presenti pizze a listino, ci scusiamo per il disagio</h3>
}
else
{
    <main class="container">
        <h1>Il nostro olimpo</h1>
        <table class="table table-hover my-5">
            <thead>
                <tr>
                    <th scope="col">Nome</th>
                    <th scope="col"></th>
                    <th scope="col">Descrizione</th>
                    <th scope="col">Prezzo</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (Pizza pizza in Model)
                {
                    <tr>
                        <td><a href="@Url.Action("Dettagli","Pizza",new{ID=pizza.Id})">@pizza.Nome</a></td>
                        <td><img src="@pizza.Immagine" class="img-fluid" alt="@pizza.Nome" width="300"></td>
                        <td>@pizza.Descrizione</td>
                        <td>@pizza.Prezzo €</td>
                        <td><a class="btn btn-primary" href="@Url.Action("ModificaPizza","Pizza", new{ID=pizza.Id})">Modifica Pizza</a></td>
                        <td><a class="btn btn-danger" href="@Url.Action("EliminaPizza","Pizza", new{ID=pizza.Id})">Elimina Pizza</a></td>
                    </tr>
                }
            </tbody>
        </table>
        <a class="btn btn-primary" href="@Url.Action("NuovaPizza","Pizza")">Aggiungi Pizza</a>
    </main>
}

la mia pizzeria/Views/Pizza/ModificaPizza.cshtml
@model CategoriaPizzaView

<div class="container">
    <form asp-controller="Pizza" asp-action="ModificaPizza">
        @Html.AntiForgeryToken()
        <input asp-for="Pizza.Id" type="hidden" class="form-control">
        <div class="mb-3">
            <label>Nome Pizza:</label>
            <input asp-for="Pizza.Nome" type="text" class="form-control">
            <span asp-validation-for="Pizza.Nome" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Descrizione Pizza:</label>
            <textarea asp-for="Pizza.Descrizione" type="text" class="form-control"></textarea>
            <span asp-validation-for="Pizza.Descrizione" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Prezzo Pizza:</label>
            <input asp-for="Pizza.Prezzo" type="text" class="form-control">
            <span asp-validation-for="Pizza.Prezzo" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Immagine Pizza:</label>
            <input asp-for="Pizza.Immagine" type="text" class="form-control">
            <span asp-validation-for="Pizza.Immagine" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Categoria:</label>
            <select asp-for="Pizza.CategoriaNome" rows="10" class="d-block w-100">
                <option value=""></option>
                @foreach (Categoria categoria in Model.Categorie)
                {
                    <option value="@categoria.Nome">@categoria.Nome</option>
                }
            </select>
            <span asp-validation-for="Pizza.CategoriaNome" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Ingredienti:</label>
            <select asp-for="ListaIdIngredienti" asp-items="@Model.ListaIngredienti" multiple size="10" class="form-control mb-2 mr-sm-2 ml-sm-3 leftList">
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

la mia pizzeria/Views/Pizza/NuovaPizza.cshtml
@model CategoriaPizzaView

<div class="container">
    <form asp-controller="Pizza" asp-action="NuovaPizza">
        @Html.AntiForgeryToken()
        <div class="mb-3">
            <label>Nome Pizza:</label>
            <input asp-for="Pizza.Nome" type="text" class="form-control">
            <span asp-validation-for="Pizza.Nome" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Descrizione Pizza:</label>
            <textarea asp-for="Pizza.Descrizione" type="text" class="form-control"></textarea>
            <span asp-validation-for="Pizza.Descrizione" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Prezzo Pizza:</label>
            <input asp-for="Pizza.Prezzo" type="number" class="form-control">
            <span asp-validation-for="Pizza.Prezzo" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Immagine Pizza:</label>
            <input asp-for="Pizza.Immagine" type="text" class="form-control">
            <span asp-validation-for="Pizza.Immagine" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Categoria:</label>
            <select asp-for="Pizza.CategoriaNome" rows="10" class="d-block w-100">
                <option value=""></option>
                @foreach(Categoria categoria in Model.Categorie)
                {
                    <option value="@categoria.Nome">@categoria.Nome</option>
                }
            </select>
            <span asp-validation-for="Pizza.CategoriaNome" class="text-danger"></span>
        </div>
            <div class="mb-3">
                <label>Ingredienti:</label>
                <select asp-for="ListaIdIngredienti" asp-items="@Model.ListaIngredienti" multiple size="10" class="form-control mb-2 mr-sm-2 ml-sm-3 leftList">
                </select>
            </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>